$(call inherit-product,
$(SRC_TARGET_DIR)/product/aosp_base.mk
#
DEVICE_PACKAGE_OVERLAY:=

PRODUCT_PACKAGE+=
PRODUCT_COPY_FILES+=
PRODUCT_NAME:= full_f488
PRODUCT_DEVICE:= f488
PRODUCT_MODEL:= Android for Irarref F488
